# Methods

## Entropy and Distance Measures 

The class of functions that describe the difference between two probability distributions $P$ and $Q$ is defined in general as:

$$D_f(P||Q) = \int \mathcal{f} \left( \frac{dP}{dQ} \right) dQ$$



## Predicting Hydrological Signatures from Catchment Attributes

{cite}`mcmillan2021review` presents a comprehensive review of approaches to hydrological signature prediction from catchment attributes, covering a large number of signatures and their links to hydrological processes.  Several signatures relate to specific exceedance percentiles, which may be seen as first order characteristics since they represent positions in the FDC, and others may be seen as second order since they describe slopes (for example the slope of the FDC between the log-transformed 33rd and 66th streamflow percentiles).  The mean is a summary statistic in the sense that it encapsulates all observations.  F-divergence measures are more closely aligned with these latter signatures since they characterize the full distribution, however the test setup is different in the case of testing predictability of divergence metrics due to the target variable being a function of two probability distributions representing two locations.  

The capacity of catchment attributes to predict hydrological signatures has been shown to be linked to spatial smoothness {cite}`addor2018ranking`.  Two levels of model complexity are tested in this study.  The first is a binary classification model which tests the model's ability to predict whether a regional donor/proxy catchment provides a more informative model (smaller f-divergence) than the maximum uncertainty prior (uniform model Q).  The second is a nonlinear regression model that outputs predictions of the target variables.  A summary of tests is provided in {numref}`model-summary-table`.


```{list-table} Summary of Model Scenarios
:header-rows: 1
:name: model-summary-table

* - Number
  - Target Variable
  - Description
  - Variations
* - 1
  - Mean Daily Discharge (MD)
  - Predict the mean daily discharge (mm/day) using catchment attributes.  
  - Vary the ordering of catchment attribute groups to test influence of groups of related attributes, test randomized attributes.
* - 2
  - Shannon Entropy (H)
  - Predict H computed from unit area runoff distributions at single locations from catchment attributes.
  - Vary the encoding dictionary size between 4, 6, 8, 9, 10, 11, and 12 bits.
* - 3
  - KL Divergence
  - Predict the Kullback-Leibler (KL) divergence of pseudo-simulated (Q) from observed (P) unit area runoff distributions between pairs of locations from catchment attributes.
  - Vary the encoding dictionary size between 4 and 12 bits, vary the prior applied to Q, test concurrent and nonconcurrent periods of record, test the effect of probabilistic treatment of observation error (10% uniform).
* - 4
  - Earth Mover's Distance (EMD)
  - Predict the EMD between observed (Q) and pseudo-simulated (P) unit area runoff distributions between pairs of locations from catchment attributes.
  - Vary the encoding dictionary size between 4 and 12 bits, test concurrent and nonconcurrent periods of record, test the effect of probabilistic treatment of observation error (10% uniform).
* - 5
  - Total Variation Distance (TVD)
  - Predict the total variation distance between observed (Q) and pseudo-simulated (P) unit area runoff distributions between pairs of locations from catchment attributes.
  - Vary the encoding dictionary size between 4 and 12 bits, test concurrent and nonconcurrent periods of record, test the effect of probabilistic treatment of observation error (10% uniform).
```

### Mean Daily Discharge (MDD) & Mean (Unit Area) Runoff (MUR)
{cite}`addor2018ranking` predicts mean daily discharge from catchment attributes for approximately 600 catchments over the continental US from the CAMELS {cite}`arsenault2020comprehensive` dataset.  A similar approach is taken to replicate those results here:  

$$\text{MDD}(X) = \frac{1}{n} \sum_{i=1}^n X_i \quad mm/day$$

The conversion from $\frac{1 m^3}{s}$ to $86.4 \frac{mm}{day}$ is $\frac{1 m^3}{s} \cdot \frac{3600s}{1h} \cdot \frac{24h}{1day} \cdot \frac{1000mm}{1m} \cdot \frac{1 \text{km}^2}{(1000m)^2} \cdot \frac{1}{A_{catchment} \text{km}^2}$.

The MUR units are expressed in $\frac{L}{s \cdot \text{km}^2}$ converted from $\frac{m^3}{s}$ by multiplying by $\frac{1000 L}{m^3}$ and dividing by the drainage area ($A_{catchment}$) in $\text{km}^2$


### Shannon Entropy

{cite}`shannon1948mathematical` describes entropy as a measure of the uncertainty or randomness in a probability distribution. It quantifies the amount of information required to describe the state of a system. For a discrete random variable $X$ with possible outcomes (states) ${x_1, x_2, \dots, x_n}$ and corresponding probabilities $P(X=x_i) = p_i$, the Shannon entropy $H(X)$ is defined as:

$$H(X) = -\sum_{i=1}^n P(x_i) \log_2 P(x_i)$$

### Kullback-Leibler Divergence

KL divergence is a measure of how one probability distribution diverges from a second, expected probability distribution. It quantifies the amount of information lost when approximating one distribution with another. Mathematically, for two discrete probability distributions $P(X)$ and $Q(X)$ over the variable $X$, the KL divergence from $Q$ to $P$ is defined as (note here we use the log base 2 to represent bits, where the base e for "nats" is sometimes used):

$$D_{KL}(P(X)||Q(X)) = \sum_{i=1}^n P(x_i) \log_2\frac{P(x_i)}{Q(x_i)}$$

In the context of observed streamflow, KL divergence can be used to compare the true distribution of streamflow values at a given location (derived from measurements) to a modelled or assumed distribution. For example, given a simple model that predicts streamflow at ungauged locations, KL divergence helps us quantify how much information is missing or lost when a model’s predictions are used instead of having actual observed values.  It represents the extra number of yes or no questions you would have to ask on average to get the correct answer above the minimum number of yes or no questions required given perfect frequency estimates.  The optimal sequence of yes or no questions simply divides the overall probability into as close to 50/50 as possible each time until an unambiguous answer is arrived at.  Imperfect frequency estimates result in sub-optimally dividing the space when asking yes/no questions, so a few more questions must be asked in the long run.  The children's board game Guess Who is an excellent example.

* In the information theory literature, the KL divergence is described as the inefficiency in the encoding dictionary due to incorrect estimation of the frequency of symbols or states.
    * The Kolmogorov complexity represents a lower bound on optimal encoding.
    * The optimality of encoding translates to the average length of message transmitted, expressed in bits
    * A model that is better than random guessing represents signal compression
    * There is a fundamental link between compression and prediction.  "A model that compresses well generalizes well" (HUTTER).

### Total Variation Distance

Total Variation Distance (TVD) is a measure of the difference between two probability distributions. It quantifies the maximum difference in probabilities assigned to the same events (states) by two distributions. For two discrete probability distributions $P$ and $Q$ over the variable $X$, the TVD is defined as:

$$\text{TVD}(P,Q) = \frac{1}{2}\sum_i|P(x_i) - Q(x_i)|$$

In the context of observed streamflow, TVD can be used to compare the true distribution of streamflow values at a given location (derived from measurements) to a modelled or assumed distribution. For example, if we have a model that predicts streamflow at various locations, TVD describes the **maximum discrepancy** between the model’s predictions and the actual observed values.

### Earth Mover's Distance

The Earth Mover's Distance (EMD), is a (bipartite) network flow minimization problem.  Bipartite simply means we have graphs, in this case probability mass functions of the proxy and target runoff distributions $P$ and $Q$, with edges joining $p_i$ to $q_i$ and no edges within $P$ or within $Q$.  

The distance describes the difference between the two probability distributions in terms of the total distance the probability mass must be moved to transform one distribution to another. For two discrete probability distributions $P$ and $Q$ over the variable $X$, the EMD is defined from {cite}`emd_1998` as the minimum cost:

$$\sum_{i\in P} \sum_{j\in Q} c_{ij}f_{ij}$$

Subject to:

$$f_{ij} \geq 0 \quad i\in P, j \in Q$$
$$\sum_{i\in P} f_{ij} = y_j \quad j \in Q$$
$$\sum_{j\in Q} f_{ij} \leq x_i \quad i\in P$$

Where $x_i$ is the frequency of the proxy $p_i$ and $y_j$ is the "capacity" if each state $q_i$, or the difference between $p_i$ and $q_i$.  The first constraint prevents negative flows $f_{ij}$, which means balances can't be met by moving "mass" from $p_i$ to $q_i$, and instead it must be moved "laterally" at a cost of $c_{ij}$, or the distance from state $i$ to state $j$.

In the context of observed streamflow, the EMD can be used to compare the true distribution of unit area runoff at a given location (derived from measurements) to a modelled or assumed distribution. For example, if we have a model that predicts streamflow at various locations, the EMD helps us quantify how different the predicted distribution is from the distribution of observed values in the same units of the distributions, in this case UAR ($L/s/\text{km}^2$).

## Predictive Model

### Gradient Boosted Decision Trees

Gradient Boosting Decision Tree (GBDT) is a widely used machine learning algorithm that builds an ensemble of (simple) decision trees in a sequential manner. Each tree is trained to correct the errors of the previous trees, gradually improving the overall prediction accuracy. The method combines the strengths of decision trees with boosting, a technique that focuses on balancing the model's bias and variance.

General procedure:

1. **Initialization**: The algorithm starts with an initial prediction, often the mean of the target values.
2. **Iterative Learning**: In each iteration, a new decision tree is trained to predict the residual errors (differences between the actual values and the current predictions).
3.  **Gradient Descent**: The algorithm uses gradient descent to minimize the loss function, guiding the training of each new tree to correct the errors of the ensemble.
4. **Combination**: The predictions of all trees are combined to form the final prediction, typically by summing the weighted outputs of the trees.

The GBDT model is selected for their strength in detecting nonlinear relationships from high-dimensional input feature sets, for the ability to set up training and testing for robust model training, and for the ability to test relative importance of features.  One advantage of GBDT over the random forest (RF) approach used in {cite}`addor2018ranking` for hydrological signature prediction from attributes is **the training data is not limited by incomplete feature sets** -- rather the ensemble tree construction method, which uses random subsamples of both rows and columns, allows samples with missing attributes to remain in the training data.

### Application of GBDT for Predicting Entropy and Divergence Measures

In the context of predicting various information and divergence measures, GBDT can be used to model complex relationships between features and target variables. We use GBDT models to capture nonlinear patterns and predict KL divergence, Total Variation Distance, and Earth Mover's Distance by learning from a large set of catchment attributes.

### Model Validation / Testing

To address the problem of overfitting, 5-fold cross validation is done on a training dataset which is separated at the outset from a test set to prevent information leakage from training to validation.  The GBDT model procedure is carried out as follows: 

1. Split the data into 90% training and 10% testing.  Note that the split is done by station id, not by row since rows contain pairwise information.  Since data from two stations is contained in each row, separating by station ID ensures that data from stations in the training set do not "leak" into the held-out test set.  
2. Run a number of cross validation tests on the training data while randomly permuting the gradient boosting hyperparameters.  The purpose of this step is to a) optimize over the hyperparameters, and b) find the hyperparameter set that yields the best average validation score.
3. Retrain a model using the full training set based on the (approximately) optimal hyperparameters, generate predictions on the hold-out test set to determine the model performance on unseen data.
4. (Possibly) repeat steps 1-3 several times to evaluate selection bias in the hold-out set.

## Graph Partitioning

The first two predictors are computed on data from individual streamflow monitoring locations.  The subsequent three predictors (f-divergences) are computed on pairs of catchments.  The pairwise setup adds complexity to the train-test split since the input data now represent a network graph that must be partitioned in such a way to avoid data leakage.  Partitioning a highly connected graph is NP-hard, but we simply segment by alternate node colouring and cut all edges between the k colours -- meaning the sample represents only edges between nodes of the same colour.

### Train-Test Split

The input dataset is pairwise comparisons of just over 1300 (streamflow) monitored catchments, their attributes, and the attribute differences.  After filtering for data concurrency (minimum 1 year, < 5 days missing per month) and maximum distance between basin centroids (500 km) we are left with roughly 225K pairs.  The pairwise setup means that station data appears in more than one row.  As a result, the attributes of stations can end up in both training and test sets if we simply split by randomly assigning rows to training or test sets.   We can't simply cut edges until the graph is separated because it is a [generalization of the "keeping a subset of vertices" problem in graph theory which is NP-hard](https://en.wikipedia.org/wiki/Independent_set_(graph_theory)).

To address this issue we split the dataset spatially to create partitioned datasets for each fold and draw samples from within the "cluster" while filtering all edges between the fold and the rest of the set.  The end goal is to generate training folds where the official_id does not appear in both training and test set, in either proxy or target column.  One problem remains, and that is to generate training and test sets with some assurance that the target variable distributions match to some degree, but this is less critical than ensuring there is no data leakage between training and test data.  

Next we create training/test splits and visualize how the target variable distributions compare.

### Pre-load results

In [1]:
import os
import numpy as np
import pandas as pd
import xyzservices.providers as xyz
from bokeh.io import output_notebook
from pathlib import Path

import geopandas as gpd

from shapely.geometry import Point

from bokeh.plotting import figure, show
from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.palettes import Sunset10, Category20

from sklearn.cluster import AgglomerativeClustering
output_notebook()

In [2]:
BASE_DIR = os.getcwd()

tiles = xyz['USGS']['USTopo']
nrows = None
# open an example pairwise results file
input_folder = os.path.join(
    BASE_DIR, "data", "processed_divergence_inputs",
)

# the input data file has an associated revision date
revision_date = '20250820'

all_test_results = {}
attribute_set_names = ['climate', '+terrain', '+land_cover', '+soil']

In [3]:
# load the catchment characteristics
fname = 'BCUB_watershed_attributes_with_centroids_20260203.geojson'
attr_gdf = gpd.read_file(os.path.join('data', fname))
attr_gdf.columns = [c.lower() for c in attr_gdf.columns]
station_ids = attr_gdf['official_id'].values
print(f'There are {len(station_ids)} monitored basins in the attribute set.')

There are 1307 monitored basins in the attribute set.

In [4]:
n_folds = 20
linkage = 'ward'
pts = attr_gdf[['official_id', 'centroid_lat_deg_n', 'centroid_lon_deg_e']].copy()
lon, lat = 'centroid_lon_deg_e', 'centroid_lat_deg_n'
agg_clustering = AgglomerativeClustering(linkage=linkage, distance_threshold=None, n_clusters=n_folds)
pts['cluster'] = agg_clustering.fit_predict(pts[[lon, lat]])
pts['geometry'] = pts.apply(lambda row: Point(row[lon], row[lat]), axis=1)
pts = gpd.GeoDataFrame(pts, crs='EPSG:4326')
pts.to_crs(3857, inplace=True)

min_points_per_cluster = 30

# Post-processing: Check and handle clusters with fewer points than the threshold
cluster_sizes = pts['cluster'].value_counts()

# Find clusters with fewer points than the minimum threshold
small_clusters = cluster_sizes[cluster_sizes < min_points_per_cluster].index

# Find points in the larger clusters
large_clusters = cluster_sizes[cluster_sizes >= min_points_per_cluster].index
large_cluster_points = pts[pts['cluster'].isin(large_clusters)]

# Reassign points in small clusters individually
for small_cluster in small_clusters:
    # Find points in the small cluster
    small_cluster_points = pts[pts['cluster'] == small_cluster]
    
    # For each point in the small cluster, find the nearest point in the large clusters
    for idx, row in small_cluster_points.iterrows():
        # Compute distances to all points in the larger clusters
        distances = large_cluster_points.geometry.distance(row['geometry'])
        
        # Find the nearest large cluster
        nearest_large_cluster = large_cluster_points.loc[distances.idxmin(), 'cluster']
        
        # Reassign this point to the nearest large cluster
        pts.at[idx, 'cluster'] = nearest_large_cluster

# Output the corrected clusters and remap to make continuous numbering
# unique_clusters = pts['cluster'].value_counts()
unique_clusters = sorted(pts['cluster'].unique())
cluster_mapping = {old: new for new, old in enumerate(unique_clusters)}  # Create mapping old -> new
pts['cluster'] = pts['cluster'].map(cluster_mapping)  # Apply the renumbering
pts.head()

,official_id,centroid_lat_deg_n,centroid_lon_deg_e,cluster,geometry
0,05010500,48.966430,-113.795291,6,POINT (-12667633.878 6269167.202)
1,05012000,48.978384,-113.854464,6,POINT (-12674220.996 6271194.478)
2,05014000,48.747303,-113.698325,6,POINT (-12656839.593 6232092.278)
3,05014500,48.782578,-113.706724,6,POINT (-12657774.65 6238049.661)
4,05017500,48.721542,-113.565910,6,POINT (-12642099.29 6227744.314)

In [5]:
def format_fig_fonts(fig, font_size=20, font='Bitstream Charter', legend=True):
    fig.xaxis.axis_label_text_font_size = f'{font_size}pt'
    fig.yaxis.axis_label_text_font_size = f'{font_size}pt'
    fig.xaxis.major_label_text_font_size = f'{font_size-2}pt'
    fig.yaxis.major_label_text_font_size = f'{font_size-2}pt'
    fig.yaxis.axis_label_text_font = font
    fig.xaxis.axis_label_text_font = font
    fig.xaxis.major_label_text_font = font
    fig.yaxis.major_label_text_font = font
    if legend == True:
        fig.legend.label_text_font_size = f'{font_size-2}pt'
        fig.legend.label_text_font = font
    return fig

In [6]:
f_unique, f_counts = np.unique(pts['cluster'], return_counts=True)
count_sum = sum(f_counts)
n_clusters_created = len(f_counts)
print(f'{n_clusters_created} clusters, {count_sum} total stations')
f_counts

14 clusters, 1307 total stations

array([106, 117,  94, 260, 105,  93, 108,  84,  55,  37,  39,  73,  52,
        84])

### Plot the spatial partitions

In [7]:
# Assuming 'attr_gdf' is your GeoDataFrame and 'cluster' is the column for cluster IDs
# Convert to a ColumnDataSource for Bokeh
pts['lat'] = pts.geometry.y
pts['lon'] = pts.geometry.x
foo = pts[[c for c in pts.columns if c != 'geometry']].copy()
source = ColumnDataSource(foo)

# Define glyph shapes and colors
glyphs = ['circle', 'square', 'triangle', 'diamond', 'inverted_triangle']  # glyphs
colors = Category20[15]  # 2 colors * 5 glyphs = 10 unique symbols

# Create a function to map clusters to glyph and color
def map_cluster_to_glyph_color(cluster_id):
    cluster_id = int(cluster_id)  # Ensure cluster_id is an integer
    return glyphs[cluster_id % len(glyphs)], colors[cluster_id % len(colors)]

# Create a Bokeh plot
p = figure(title="Spatial Partitioning of Separate Clusters", 
           tools="pan,wheel_zoom,reset", match_aspect=True,  
           width=900, height=650) 

# Create a ColumnDataSource for plotting 
for cluster_id in pts['cluster'].unique(): 
    # Get marker and color for each cluster 
    marker, color = map_cluster_to_glyph_color(cluster_id) 
    
    # Filter data for the current cluster 
    cluster_data = pts[pts['cluster'] == cluster_id][[c for c in pts.columns if c != 'geometry']] 
     
    # Plot using scatter with the marker and color 
    p.scatter('lon', 'lat', source=cluster_data, marker=marker, size=5,  
              color=color, legend_label=f'{cluster_id}', 
             line_color='black', line_alpha=0.5, line_width=1) 
 
# Customize the plot 
p.add_tile(tiles, retina=True) 
p.grid.visible = False 
# Customize and sort the legend 
p.legend.title = "Fold #" 
p.legend.ncols = 1  
p.legend.label_text_font_size = '8pt' 
p.legend[0].items = sorted(p.legend[0].items, key=lambda t: f'{int(t.label.value):02d}') 
p.add_layout(p.legend[0], 'right') 

# Show the plot
show(p)

Clusters could be defined by spatial proximity, but this leads to a highly imbalanced distribution of cluster sizes and physiographic characteristics.  It is desirable to partition the graph in such a way that balances these factors.

### In the network graph, find the "exceedance" of connection distances

In [ ]:
# create a dictionary of Point geometries for each station location
station_locations = {row['official_id']: row['geometry'] for idx, row in attr_gdf.iterrows()}
# apply the point geometries to kl_df to get the distance between station_i and station_j
b = 8
kld_pairs_batch_folder = Path(BASE_DIR) / 'data' / 'kld_batches' / f'{b}_bits'

kld_pairs_batch_fpath = kld_pairs_batch_folder / f'pairwise_kld_{b}_bits_kde.csv'

assert os.path.exists(kld_pairs_batch_fpath), f'File {kld_pairs_batch_fpath} does not exist. Please run the precursor notebook to generate pairwise KL divergence results.'
kl_df = pd.read_csv(kld_pairs_batch_fpath, nrows=nrows, low_memory=False, dtype={'donor': str, 'target': str})
# drop rows where donor == target
kl_df = kl_df[kl_df['donor'] != kl_df['target']]
print(f'    processing {len(kl_df)} pairs for {b} bits')
# compute pairwise distances in km
kl_df['centroid_distance_km'] = kl_df.apply(
    lambda row: int(station_locations[row['donor']].distance(station_locations[row['target']]) / 1000)
    if row['donor'] in station_locations and row['target'] in station_locations else np.nan,
    axis=1
)
# kl_df.to_csv(kld_pairs_batch_fpath, index=False)

    processing 532170 pairs for 8 bits

In [11]:
graph_df = kl_df.copy()
# sort the values
dist_based_samples = []
distance_limits = np.arange(50, 1010, 10)
for max_distance in distance_limits:
    n_edges = len(graph_df[graph_df['centroid_distance_km'] <= max_distance])
    dist_based_samples.append(n_edges)

In [12]:
dfig = figure(title='', width=500, height=300)
src = ColumnDataSource({'x': distance_limits, 'y': dist_based_samples})
dfig.line('x', 'y', color='dodgerblue', line_width=3, source=src)
dfig.xaxis.axis_label = r'$$\text{Max. Distance [km]}$$'
dfig.yaxis.axis_label = r'$$\text{Sample Size}$$'
dfig = format_fig_fonts(dfig, legend=False, font_size=12)

show(dfig)

### Visualize the distribution of the number of neighbours per node under different maximum spatial distance limits

In [13]:
# edge_counts = pd.concat([graph_df['proxy'], graph_df['target']]).value_counts()
# Function to compute the CDF
def compute_cdf(data):
    sorted_data = np.sort(data)
    cdf = np.arange(1, len(sorted_data) + 1) / len(sorted_data)
    return sorted_data, cdf

# Initialize a dictionary to hold CDF data for each threshold
cdf_data = {}
# Define distance thresholds for the CDFs
distance_thresholds = np.arange(100, 1100, 100)
# Loop through each distance threshold and compute the CDF of the number of edges per node
for max_distance in distance_thresholds:
    # Filter the DataFrame for the current threshold
    filtered_df = graph_df[graph_df['centroid_distance_km'] <= max_distance]
    
    # Count the number of edges per node (degree)
    edge_counts = pd.concat([filtered_df['donor'], filtered_df['target']]).value_counts()
    
    # Compute the CDF for this threshold
    sorted_counts, cdf = compute_cdf(edge_counts)
    
    # Store the data for plotting later
    cdf_data[max_distance] = (sorted_counts, cdf)

# Plot the CDF for each distance threshold
cplt = figure(title='CDF of Edges per Node by Distance Threshold', 
              # x_axis_type='log', 
              width=600, height=350)

n=0
for max_distance in distance_thresholds:
    sorted_counts, cdf = cdf_data[max_distance]
    cplt.line(sorted_counts, cdf, line_width=3,
              legend_label=f'd <= {max_distance}km', color=Sunset10[n])
    n += 1

# Add plot labels and legend
cplt.xaxis.axis_label = r'$$\text{Number of Edges (Degree)}$$'
cplt.yaxis.axis_label = r'$$P(X \leq x)$$'
cplt.add_layout(cplt.legend[0], 'right')
cplt.legend.click_policy = 'hide'
cplt = format_fig_fonts(cplt, font_size=12)
show(cplt)

## Visualize the Spatial Distribution of Degree

The degree represents the number of edges connecting a node to the rest of the graph.   Determine the number of edges from each node and plot a heat map to reflect the spatial distribution of degree.  Set a logartithmic colour bar to highlight the wide range of network connectivity.  Set a few distance limits to see how the network connectivity changes in space when varying the distance threshold.

In [14]:
# Compute degree
def compute_degree(graph_df, distance_threshold=1000):
    df = graph_df[graph_df['centroid_distance_km'] <= distance_threshold].copy()
    in_degree = df['donor'].value_counts()
    out_degree = df['target'].value_counts()
    degree = in_degree.add(out_degree, fill_value=0).reset_index()
    degree.columns = ['node', 'degree']
    degree['lon'] = degree.apply(lambda r: attr_gdf.loc[attr_gdf['official_id'] == r['node'], 'geometry'].x.values[0], axis=1)
    degree['lat'] = degree.apply(lambda r: attr_gdf.loc[attr_gdf['official_id'] == r['node'], 'geometry'].y.values[0], axis=1)
    return degree

In [15]:
from bokeh.models import (LogColorMapper, ColorBar, LogColorMapper, Whisker,
                        HoverTool, NumeralTickFormatter, PrintfTickFormatter)
from bokeh.palettes import Sunset10
from bokeh.transform import log_cmap, linear_cmap

def ticker(tick):    
    return f'{tick:.1e}'

degree_figs = []
n = 0
for dist_threshold in [1000, 700, 400, 100]:
    degree = compute_degree(graph_df, dist_threshold)
    n_nodes = len(degree)
    p = figure(width=800, height=600, title=f"Centroid dist <= {dist_threshold}km (N={n_nodes})", 
               x_axis_label='Longitude', y_axis_label='Latitude')
    p.add_tile(tiles, retina=True, alpha=0.5)
    
    # Prepare the data source for Bokeh
    source = ColumnDataSource(degree)
    color_mapper = linear_cmap(field_name='degree', palette=Sunset10, 
                               low=degree['degree'].min(), high=degree['degree'].max())
    
    # Scatter plot with discrete colors
    p.scatter('lon', 'lat', size=4., source=source,
              fill_color=color_mapper,
              line_color='black', line_alpha=0.35, alpha=0.6)
    
    # # Add a color bar
    color_bar = ColorBar(color_mapper=color_mapper['transform'], label_standoff=10, width=8, location=(0, 0),
                        major_label_text_font='Bitstream Charter', major_label_text_font_size='12pt', title='Node Degree',
                        title_text_font='Bitstream Charter', title_text_font_size='12pt')
    p.add_layout(color_bar, 'right')
    p.xaxis.formatter = PrintfTickFormatter(format='%.1e')
    p.yaxis.formatter = PrintfTickFormatter(format='%.1e')
    # Add a hover tool to display node and degree
    hover = HoverTool()
    hover.tooltips = [
        ("Node", "@node"),
        ("Degree", "@degree")
    ]
    if n in [0, 1]:
        p.xaxis.visible = False
    if n in [1, 3]:
        p.yaxis.visible = False
        
    n += 1
    p.add_tools(hover)
    degree_figs.append(p)

In [16]:
layout = gridplot(degree_figs, ncols=2, width=450, height=300)
show(layout)

Above, we see that restricting the maximum distance significantly reduces the degree of nodes.  If we restrict it to far, i.e. $(d < ~200) $ km, we begin to isolate nodes (stations) completely.

In [23]:
from bokeh.palettes import Category10_10
colours = Category10_10

def compute_empirical_cdf(data):
    percentiles = np.linspace(0, 100, 200)
    # sorted_data = np.sort(data)
    sorted_data = np.percentile(data, percentiles)
    # cdf = np.arange(1, len(sorted_data) + 1) / len(sorted_data)
    cdf = percentiles / 100.0
    return sorted_data, cdf

plots = []


kld_distribution_plot = figure(
    title=r'$$D_{KL}(\text{KDE}||\text{Discrete})$$', x_axis_type='log', width=600, height=350
    )

b = 8
# hide_y = False
# kld_pairs_fpath = Path(BASE_DIR) / 'data' / 'kld_batches' / f'kld_results_{b}bits_{revision_date}.csv'
kld_folder = Path(BASE_DIR) / 'data' / 'kld_batches' / f'{b}_bits' 
# kld_pairs_fpath = kld_folder / f'discrete_vs_kde_KLDs_{b}.csv'
kld_pairs_fpath = kld_folder / f'pairwise_kld_{b}_bits_kde.csv'
kl_df = pd.read_csv(kld_pairs_fpath)

# count nan values in the kld column
edge_midpoints, hist = compute_empirical_cdf(kl_df['kld'].values)
kld_distribution_plot.line(x=edge_midpoints, y=hist, line_color=colours[i], 
                        line_width=2.5, alpha=0.5, legend_label=f'{b} bits')
kld_distribution_plot.legend.click_policy = "hide"
kld_distribution_plot.xaxis.axis_label = r'$$D_{KL}(P || Q)$$'
kld_distribution_plot.yaxis.axis_label = r'$$\text{Density}$$'
kld_distribution_plot.legend.location = 'top_left'
kld_distribution_plot.legend.background_fill_alpha = 0.5

/tmp/ipykernel_5719/1907162308.py:25: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  kl_df = pd.read_csv(kld_pairs_fpath)

In [24]:
show(kld_distribution_plot)

In [25]:
kl_df.head()

      donor    target       kld  centroid_distance_km
0  05017500  05014500  0.569935             12.389128
1   05AA008  05014500  1.511875            113.095724
2   05AA022  05014500  0.824940             81.608773
3   05AA023  05014500  1.893660            142.148422
4   05AA035  05014500  2.130992            137.833788

## Graph Partitioning Methods

In order to propertly test out of sample, we must ensure that data from the training set are not included in the test set.  In the case of the f-divergence measures, each sample contains information about two streamflow monitoring locations, the target and the proxy.  This problem represents a network graph, making the training/test separation a graph partitioning problem.

### Plot the CDFs of KL divergence by bitrate and prior

From the above plot, we can see that the similarity of distributions between partitions is affected by the clustering / number of folds.

### Map Colouring Partition

Instead of spatial cluster-based partitioning, try testing a partitioning using N classes partitioned by alternating classes spatially.  This will result in classes that cover the full study region but with half the points.

In [26]:
def alternate_partition_geopandas(gdf, n_classes=2):
    # Extract coordinates from the GeoDataFrame
    gdf['coords'] = gdf.geometry.apply(lambda geom: (geom.x, geom.y))
    
    # Sort by coordinates, for example, first by x and then by y
    sorted_gdf = gdf.sort_values(by=['coords'])
    
    # Alternate assignment of nodes to N classes
    sorted_gdf['class'] = np.arange(len(sorted_gdf)) % n_classes
    
    return sorted_gdf

In [27]:
gdf_copy = attr_gdf.copy().to_crs(3857)
gdf_copy['centroid_lon_deg_e'] = gdf_copy.geometry.centroid.x
gdf_copy['centroid_lat_deg_n'] = gdf_copy.geometry.centroid.y

In [28]:
n_classes = 5
sorted_gdf = gdf_copy.sort_values(by=['centroid_lon_deg_e', 'centroid_lat_deg_n'])
# Alternate assignment of nodes to N classes
sorted_gdf[f'{n_classes}_spatial'] = np.arange(len(sorted_gdf)) % n_classes

In [29]:
# Create a Bokeh plot
p = figure(title="Spatial Partitioning II", 
           tools="pan,wheel_zoom,reset", match_aspect=True, 
           width=900, height=650)

# Create a ColumnDataSource for plotting
for cluster_id in sorted_gdf[f'{n_classes}_spatial'].unique():
    # Get marker and color for each cluster
    marker, color = map_cluster_to_glyph_color(cluster_id)
    
    # Filter data for the current cluster
    cluster_data = sorted_gdf[sorted_gdf[f'{n_classes}_spatial'] == cluster_id][[c for c in attr_gdf.columns if c != 'geometry']]
    
    # Plot using scatter with the marker and color
    p.scatter('centroid_lon_deg_e', 'centroid_lat_deg_n', source=cluster_data, marker=marker, size=5, 
              color=color, legend_label=f'{cluster_id}',
             line_color='black', line_alpha=0.5, line_width=1)

# Customize the plot
p.add_tile(tiles, retina=True)
p.grid.visible = False
# Customize and sort the legend
p.legend.title = "Fold #"
p.legend.ncols = 1
p.legend.label_text_font_size = '8pt'
p.legend[0].items = sorted(p.legend[0].items, key=lambda t: f'{int(t.label.value):02d}')
p.add_layout(p.legend[0], 'right')

# Show the plot
show(p)

In [30]:
# for the clusters created above, iterate through and compute 
# the cdf for DKL in-group vs. out-group samples
cluster_cdfs = []
all_cluster_ids = []
dkl_col = f'kld'
# Create a Bokeh plot
p = figure(width=600, height=350,# title=f"Empirical CDF of {dkl_col} (AND vs. NOR)",
           x_axis_label=dkl_col, y_axis_label='Empirical CDF', x_axis_type='log')

for cluster_id in sorted_gdf[f'{n_classes}_spatial'].unique():
    # Get marker and color for each cluster
    marker, color = map_cluster_to_glyph_color(cluster_id)
    
    # Filter data for the current cluster
    cluster_data = sorted_gdf[sorted_gdf[f'{n_classes}_spatial'] == cluster_id][[c for c in sorted_gdf.columns if c != 'geometry']].copy()
    cluster_ids = cluster_data['official_id']
    all_cluster_ids += list(cluster_ids)
    
    # print(cluster_data.head(3))
    dkl_sample = kl_df.copy()
    dkl_sample.dropna(subset=[dkl_col], inplace=True)
    # test set
    dkl_sample_AND = dkl_sample[(dkl_sample['donor'].isin(cluster_ids)) & (dkl_sample['target'].isin(cluster_ids))]
    # training set
    dkl_sample_NOR = dkl_sample[(~dkl_sample['donor'].isin(cluster_ids)) & (~dkl_sample['target'].isin(cluster_ids))]
    print(f'{len(dkl_sample_NOR)}/{len(dkl_sample_AND)} train/test sample sizes')

    percentiles = np.linspace(0, 100, 200)

    # Compute the percentile values for each dataset
    percentile_values_and = np.percentile(dkl_sample_AND[dkl_col], percentiles)
    percentile_values_nor = np.percentile(dkl_sample_NOR[dkl_col], percentiles)

    # Create CDF values for each set of percentiles (from 0 to 1)
    cdf_values = percentiles / 100

    # Prepare data for Bokeh
    source_and = ColumnDataSource(data={'x': percentile_values_and, 'y': cdf_values})
    source_nor = ColumnDataSource(data={'x': percentile_values_nor, 'y': cdf_values})
    
    # Plot the CDFs
    p.line('x', 'y', source=source_and, line_width=2, color='dodgerblue', legend_label=f'Test', alpha=0.75)
    p.line('x', 'y', source=source_nor, line_width=2, color='magenta', legend_label=f'Train', alpha=0.85)
    
    
    
    # Show the plot
    p.legend.location = "bottom_right"

p.xaxis.axis_label = 'KL Divergence [bits/sample]'
p.yaxis.axis_label = r'$$P(X \geq x)$$'
p.legend.click_policy = 'hide'
p = format_fig_fonts(p, font_size=12)

376771/13000 train/test sample sizes
360760/15943 train/test sample sizes
367852/14572 train/test sample sizes
353664/17595 train/test sample sizes
354855/17328 train/test sample sizes

In [31]:
show(p)

The above shows the KL divergence across partitioned segments of the graph using a 5-colour map colouring approach.  The distributions are more similar than the spatial clustering approach and are reasonably close overall.  There is slightly more variation in the test sets.

In [32]:
sorted_gdf.to_file(f'data/stn_attributes_with_{n_classes}_spatial_partitions.geojson')

In [33]:
unique, counts = np.unique(sorted_gdf[f'{n_classes}_spatial'], return_counts=True)
print(unique)
counts

[0 1 2 3 4]

array([262, 262, 261, 261, 261])

From {cite}`nguyen2009surrogate`:

>"An interesting example of this more elaborate formulation is a “distributed detection” problem, in which individual components of the d-dimensional covariate vector are measured at spatially separated locations, and there are communication constraints that limit the rate at which the measurements can be forwarded to a central location where the classification decision is made."

In the example above the d-dimensional covariate vector X represents d independent observation points with their own signals.  The quantizer Q is the decision of how to map the signals of Q to some lower dimension such that a classification can be computed in support of a decision (and action).

Given a number of sensors outputting independent signals X, where there is a communication constraint preventing the processing of the complete set of raw signals, a quantizer Q is some (fixed) mapping of X to (lower dimensional) Z.  One half of the problem is to determine Q that minimizes prediction error $P\left(Y \neq \gamma(Z)\right)$ and the other half of the problem is to determine the discriminant function that ...

Can we map the streamflow monitoring network problem in similar terms?

## The General Problem Description

Consider the set of points defining river network confluences as a space of potential locations to monitor streamflow.  A simple approach to predicting streamflow in unmonitored basins (PUB) might be to assume: 
1) a range of streamflow that could occur $[a, b]$, and
2) a prior distribution over some set of states $\omega$ defining streamflow at a point in time.

The states could be defined in relation to some application of interest, or in relation to measurement error/uncertainty.  For example, if the rating curve (stage-discharge relationship) uncertainty is 10% for flows between 0 and 1 $m^3/s$, the appropriate precision is in the order of $0.1 m^3/s$, or to define ten states (discrete intervals) between 0 and 1.  The definition of states is referred to as the quantization of the streamflow signal.

Observing streamflow at one location provides information that can be used to predict streamflow at other locations.  A simple and common first approximation for prediction in ungauged basins (PUB) is to assume the discharge at distinct locations is equal on a unit area basis (UAR model).  This is a reasonable and useful assumption where the locations receive similar climate inputs due to close spatial proximity, or where the catchments are similar in terms of the characteristics related to the mechanisms governing the rainfall runoff response, such as the vegetation, soil, or slope which play a role in how water moves across the surface, into and through the soil, and into the atmosphere.  

A **proxy** location is a monitored catchment whose observations can be used to estimate runoff at a **target** location defining a different catchment. Both locations are watersheds, defined as land areas where all precipitation drains to a common outlet.  A simple PUB model uses the distribution of UAR $(\mathbf{Q})$ at a proxy location to estimate the distribution of UAR $(\mathbf{P})$ at a target location.  Both locations can be characterized by a set of measurable attributes associated with the rainfall-runoff response.

The goal in this exercise is to select the sensor location (or N locations as resources permit) that minimizes the probability of prediction error, in this case incorrect frequency estimation across the unmonitored space.  Stated in another way, the goal is to determine how to prioritize adding stations in such a way as to maximize the expected reduction in uncertainty over the unmonitored space.  The expectation of uncertainty reduction from adding a sensor (monitoring station) is estimated by developing a relationship between catchment attributes and the similarity of $(\mathbf{P})$ and $(\mathbf{Q})$.  In cases where minimizing the probability of error is intractable (support why, namely), f-divergences have been used as surrogates for probability of error (Blackwell 1951, Nguyen/Jordan 2009).  (An f-divergence is defined as any convex function of the likelihood ratio.)

Extending the example of the UAR PUB model above, assuming the maximum uncertainty prior uniform distribution $\mathbb{U}$ over $\omega$ is in many cases a better model for $\mathbf{P}$ than $\mathbf{Q}$.  "Better" in this case means the distributions are more similar, or that the expected message length to transmit observations matching the true distribution is greater than the naive assumption that all states are equally probable.  This feature leads to a possible binary classification /  prediction problem:

## Binary prediction formulation 

Consider an unmonitored stream network where we assume a uniform prior distribution at all possible observation locations.  It is not the case that adding a sensor in some location will provide predictive information for all unmonitored locations.  For many catchments, the uniform prior will be closer to the "true" distribution $\mathbf{P}$.  The term "true" refers to the distribution based on the set of observations held out of sample for computing the loss.  The probability that a potential monitoring location is a "better" proxy than the uniform prior for the UAR distribution at another location describes a binary prediction problem formulation (test the balance of data across bitrates!).  

The discriminant function is what quantifies a proxy distribution as "better", and since the minimization of prediction error in such a formulation is not readily computable or intractable (because?), determine the f-divergence that maps to an equivalent (loss or discriminant) function that is a (consistent) surrogate of prediction error.  The f-divergences are profiled for consistency are the total variation distance (TVD), the Kullback-Leibler divergence (KLD), and the Earth Mover's Distance (EMD), also known as the Wasserstein distance.

Given a covariate vector $\mathbf{X}$ of catchment attributes representing proxy (model) and target (predicted) catchments and a quantization $\mathbf{C}$ mapping streamflow $\mathbf{S}$ from continuous to discrete $\mathbf{Z}$.  $\mathbf{P}$ and $\mathbf{Q}$ are proxy and target distributions of $\mathbf{Z}$.  The discriminant is then a multi-part problem where (what is known and what isn't?) 

From {cite}`nguyen`, the total variational distance is the f-divergence consistent with the 0-1 loss in the in procedures that optimize simultaneously over the discriminant function $\gamma$ and the quantizer $Q$.

* the loss function penalizes incorrect predictions that a proxy location UAR distribution is a better "model" than the uniform distribution when it actually isn't. The goal is to miminize the (Bayes) error $R_{\textbf{Bayes}}(\gamma, C) := \mathbb{P} \left(Y \neq \text{sign}(D_{KL}(\mathbf{P}||\mathbb{U}) - D_{KL}(\mathbf{P}||\mathbf{Q}) \right)$
* For each f-divergence, there is a 1 to many mapping of divergence to loss function that is consistent.  There is a set of loss functions that yield (Bayes) consistency, that is that approach the "true" value as the sample size increases.

$$\text{min } P \left(Y \neq \gamma (X, C(S) \rightarrow Z) \right)$$




$$\text{min } P \left(D_{KL}(P||Q) < D_{KL}(P|| \mathbb{U} ) |X \right)$$

### Universal equivalence among surrogate loss functions

For a given (general, i.e. not necessarily 0-1) surrogate loss function, $\phi$-risk cak be represented as $R_{\phi}(\gamma, \mathbf{Q}) = \sum_x \phi (\gamma(z))\mu(z) + \phi(-\gamma(z))\pi(z)$

Take the infimum over the discriminant function:
* **Infimum (inf)**: The infimum of a set is the greatest value that is less than or equal to every element of the set. It is a type of "lower bound." In cases where the set has a minimum value, the infimum is equal to the minimum. However, if the set does not have a minimum (but has a lower bound), the infimum is the largest value that is not exceeded by any element of the set.

## Citations

```{bibliography}
:filter: docname in docnames
```